do not send "MISSING:" over dbus; clarify a message in debuginfo installer
Signed-off-by: Denys Vlasenko <vda.linux@googlemail.com>

diff --git a/src/Daemon/abrt-debuginfo-install b/src/Daemon/abrt-debuginfo-install
--- a/src/Daemon/abrt-debuginfo-install
+++ b/src/Daemon/abrt-debuginfo-install
@@ -148,7 +148,7 @@ print_package_names() {
 	yumopts="-C"
 	echo "`count_words $missing_debuginfo_files` missing debuginfos, getting package list from cache" >&2
     else
-	echo "`count_words $missing_debuginfo_files` missing debuginfos, getting package list" >&2
+	echo "`count_words $missing_debuginfo_files` missing debuginfos, getting package list from repositories" >&2
     fi
     local cmd="yum $yumopts --enablerepo=*debuginfo* --quiet provides $missing_debuginfo_files"
     echo "$cmd" >"yum_provides.$1.OUT"
