abrt-install-ccpp-hook check configuration
Check that either full coredump or core backtrace are configured to be
saved, fail init script if neither is.

Related to #829.

Signed-off-by: Martin Milata <mmilata@redhat.com>

diff --git a/src/hooks/abrt-install-ccpp-hook.in b/src/hooks/abrt-install-ccpp-hook.in
--- a/src/hooks/abrt-install-ccpp-hook.in
+++ b/src/hooks/abrt-install-ccpp-hook.in
@@ -31,6 +31,11 @@ CORE_PIPE_LIMIT_FILE="/proc/sys/kernel/core_pipe_limit"
 CORE_PIPE_LIMIT="4"
 
 start() {
+	if ! $HOOK_BIN --test-config; then
+		echo "Invalid configuration."
+		exit 1
+	fi
+
 	cur=`cat "$PATTERN_FILE"`
 	cur_first=`printf "%s" "$cur" | sed 's/ .*//'`
 
